### ISSUE TITLE
A new version of mathics-scanner should bump a new release of Mathics

### ISSUE THREAD

**Issue by thierry-FreeBSD** [Mathics3/mathics-scanner#16]
mathics-scanner has been released to 1.1.0 and this produces an error in Mathics:
pkg_resources.DistributionNotFound: The 'Mathics_Scanner<1.1.0,>=1.0.0' distribution was not found and is required by Mathics3

**Comment by rocky** [comment]
I don't see any problem with this. 1.1.0 is for the current development version of Mathics in git which will be released probably next week. 

Although I would have like to have been able to release everything all at once, it is no longer going to be possible. 

Therefore there will occasionally be situtations where will be situtations where some libraries that have changed API are ahead of  libraries that use them. That's why we have the version mechanism.

**Comment by thierry-FreeBSD** [comment]
OK.
